#!/bin/bash
#MISE description="Lint the project using SwiftLint and SwiftFormat"
#USAGE flag "-f --fix" help="Fix the fixable issues"

set -eo pipefail

EXCLUDE="**/Generated/**,**/*.generated.swift"
PATHS=(HackerNews HackerNewsTests Modules)

if [ "$usage_fix" = "true" ]; then
	swiftformat "${PATHS[@]}" --exclude "$EXCLUDE"
	swiftlint lint --fix --strict --config .swiftlint.yml "${PATHS[@]}"
else
	swiftformat "${PATHS[@]}" --lint --exclude "$EXCLUDE"
	swiftlint lint --strict --config .swiftlint.yml "${PATHS[@]}"
fi
