name: "HackerNews"

on:
  push:
     branches:
      - dev
      - master
  pull_request:
    paths:
      - '.swiftlint.yml'
      - 'mise.toml'
      - 'project.yml'
      - ".github/workflows/**"
      - "HackerNews/**"
      - "HackerNewsTests/**"
      - "Modules/**"

jobs:
  iOS:
    name: 
    runs-on: macos-26
    strategy:
      fail-fast: false
      matrix:
        include:
          - destination: "name=iPhone 17 Pro"
            name: "iOS"
            scheme: "Debug"
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install Dependencies
        uses: jdx/mise-action@v5
      - name: Generate resources
        run: mise exec -- make swiftgen
      - name: Generate project
        run: mise exec -- xcodegen generate
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_26.6.app/Contents/Developer'
      - name: Run tests
        run: |
          bundle add fastlane
          bundle exec fastlane test
